### ISSUE TITLE
Trying to access https returns 401

### ISSUE THREAD

**Issue by jasongrishkoff** [edemaine/kadira-compose#1]
I've set my HOST=subdomain.domain.com in the .env file, but if I try access https://subdomain.domain.com:22022 it gives me a 401 response.  Seen this before?

**Comment by edemaine** [comment]
You'll want to check all the various logs to see which docker is failing.  401 suggests that maybe the certificate didn't get fetched right?  Happy to try to help more once you find some offending logs.

**Comment by jasongrishkoff** [comment]
Thanks for the blazing fast response.  I might have been off with the 22022 because 11011 also gets a 401 if I use "http", but the logging seems to work fine.

http://subdomain.domain.com:4000 works fine
https://subdomain.domain.com:4000 doesn't work (401)

Is that expected as well?

If I were to do "docker logs", which container would I be digging into?  Not much of a Docker expert :)

Edit -- I haven't tested if the logging endpoint works in a production/https environment.  Perhaps that's why I'm encountering issues?  Still, accessing the dashboard with "https" fails.

**Comment by edemaine** [comment]
`docker ps` will give you a list of all the dockers.  You can also look in the `docker-compose.yml` file to get their docker-compose names, then try `docker-compose logs <name>` to look at a specific one.  

`https://...:4000` is not supposed to work currently (alas).

`http://...:11011` and `https://...:22022` are both supposed to work.  Maybe `kadira-engine` isn't running properly?

**Comment by jasongrishkoff** [comment]
Well, if that's the case then maybe the only way for me to test is to deploy to production and see if it works with 22022, because 11011 is working just fine.  Sorry, I assumed that it https://...:4000 wasn't working that there might be a problem.

**Comment by edemaine** [comment]
I'm not sure what "production" means here, but for letsencrypt (and thus `https://subdomain.domain.com:22022` to work, `https://subdomain.domain.com` definitely needs to be visible from the outside world.

**Comment by jasongrishkoff** [comment]
My website is https://www.domain.com (hosted by Galaxy).

My Kadira instance (thanks to your docker) is running perfectly fine on http://kadira.domain.com, but visiting https://kadira.domain.com results in a 401, which I assume is because the :4000 port doesn't work with https, yes?

So when I say "production," I mean deploying my meteor app to Galaxy so that I can try to access the Kadira instance from "https://www.domain.com/" using Kadira.connect pointed to `{endpoint:https://kadira.domain.com:22022}`

Make sense?  Sorry if I'm being confusing!

**Comment by jasongrishkoff** [comment]
Okay, works like a charm on the https production.  Thanks for building this!

**Comment by edemaine** [comment]
Great, glad it's working for more than just me!
