### ISSUE TITLE
It doesn't work with mongo 3.6 (latest), but works with 3.4

### ISSUE THREAD

**Issue by solo999** [edemaine/kadira-compose#4]
I found that it is connected to cursor issue: https://github.com/Automattic/mongoose/issues/4101,
so after change to 'mongo:3.4' instead of 'mongo' in compose file, the problem was fixed

**Comment by edemaine** [comment]
Thanks for figuring this out!

**Comment by rpanjabi** [comment]
I am getting same error. Can you please help me how to update and get this resolved.

**Comment by edemaine** [comment]
@rpanjabi Did you `git pull` to update to the latest `docker-compose.yml`? (Does it have `mongo:3.4` in it?)
