### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by crapthings** [edemaine/kadira-compose#6]
![image](https://user-images.githubusercontent.com/1147704/61361321-e324de00-a8b2-11e9-85df-840a958cfb7b.png)

**Comment by crapthings** [comment]
uncomment this line

 works
https://github.com/edemaine/kadira-compose/blob/master/docker-compose.yml#L51

**Comment by edemaine** [comment]
By "uncomment this line" do you mean that you accidentally commented it out, but then uncommenting it back everything worked?

**Comment by crapthings** [comment]
LoL yes
